#!/bin/bash

${1}riak-admin bucket-type create users '{"props":{"datatype":"map"}}'
${1}riak-admin bucket-type activate users

${1}riak-admin bucket-type create private '{"props":{"last_write_wins":true}}'
${1}riak-admin bucket-type activate private